import type { SalaryRecord } from '@/types';

export const salaryRecords: SalaryRecord[] = [
  // ─── Google (8 records) ───────────────────────────────────────────────
  {
    id: 'sal_001',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1800000,
    bonus: 200000,
    stock: 800000,
    total_compensation: 2800000,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    id: 'sal_002',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2800000,
    bonus: 400000,
    stock: 1500000,
    total_compensation: 4700000,
    confidence_score: 0.92,
    is_verified: true,
  },
  {
    id: 'sal_003',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level_standardized: 'L5',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 8,
    base_salary: 4500000,
    bonus: 700000,
    stock: 3000000,
    total_compensation: 8200000,
    confidence_score: 0.88,
    is_verified: true,
  },
  {
    id: 'sal_004',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level_standardized: 'L6',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 12,
    base_salary: 6500000,
    bonus: 1200000,
    stock: 6000000,
    total_compensation: 13700000,
    confidence_score: 0.85,
    is_verified: true,
  },
  {
    id: 'sal_005',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level_standardized: 'Staff',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 15,
    base_salary: 7500000,
    bonus: 1500000,
    stock: 10000000,
    total_compensation: 19000000,
    confidence_score: 0.78,
    is_verified: false,
  },
  {
    id: 'sal_006',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level_standardized: 'L5',
    location: 'San Francisco',
    currency: 'USD',
    experience_years: 7,
    base_salary: 210000,
    bonus: 40000,
    stock: 120000,
    total_compensation: 370000,
    confidence_score: 0.93,
    is_verified: true,
  },
  {
    id: 'sal_007',
    company: 'Google',
    company_slug: 'google',
    role: 'Machine Learning Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 3200000,
    bonus: 500000,
    stock: 2000000,
    total_compensation: 5700000,
    confidence_score: 0.90,
    is_verified: true,
  },
  {
    id: 'sal_008',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level_standardized: 'Principal',
    location: 'San Francisco',
    currency: 'USD',
    experience_years: 20,
    base_salary: 350000,
    bonus: 100000,
    stock: 500000,
    total_compensation: 950000,
    confidence_score: 0.72,
    is_verified: false,
  },

  // ─── Amazon (7 records) ──────────────────────────────────────────────
  {
    id: 'sal_009',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level_standardized: 'SDE-I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1400000,
    bonus: 100000,
    stock: 500000,
    total_compensation: 2000000,
    confidence_score: 0.94,
    is_verified: true,
  },
  {
    id: 'sal_010',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level_standardized: 'SDE-II',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2500000,
    bonus: 300000,
    stock: 1200000,
    total_compensation: 4000000,
    confidence_score: 0.91,
    is_verified: true,
  },
  {
    id: 'sal_011',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level_standardized: 'SDE-III',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 8,
    base_salary: 4000000,
    bonus: 600000,
    stock: 2500000,
    total_compensation: 7100000,
    confidence_score: 0.87,
    is_verified: true,
  },
  {
    id: 'sal_012',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level_standardized: 'SDE-II',
    location: 'Seattle',
    currency: 'USD',
    experience_years: 5,
    base_salary: 165000,
    bonus: 25000,
    stock: 60000,
    total_compensation: 250000,
    confidence_score: 0.93,
    is_verified: true,
  },
  {
    id: 'sal_013',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Data Engineer',
    level_standardized: 'SDE-I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 2,
    base_salary: 1600000,
    bonus: 150000,
    stock: 600000,
    total_compensation: 2350000,
    confidence_score: 0.89,
    is_verified: true,
  },
  {
    id: 'sal_014',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level_standardized: 'L6',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 13,
    base_salary: 5800000,
    bonus: 900000,
    stock: 5500000,
    total_compensation: 12200000,
    confidence_score: 0.80,
    is_verified: false,
  },
  {
    id: 'sal_015',
    company: 'Amazon',
    company_slug: 'amazon',
    role: 'Software Development Engineer',
    level_standardized: 'SDE-III',
    location: 'Seattle',
    currency: 'USD',
    experience_years: 9,
    base_salary: 195000,
    bonus: 35000,
    stock: 90000,
    total_compensation: 320000,
    confidence_score: 0.86,
    is_verified: true,
  },

  // ─── Microsoft (6 records) ───────────────────────────────────────────
  {
    id: 'sal_016',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 2,
    base_salary: 1500000,
    bonus: 150000,
    stock: 400000,
    total_compensation: 2050000,
    confidence_score: 0.93,
    is_verified: true,
  },
  {
    id: 'sal_017',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2600000,
    bonus: 350000,
    stock: 1000000,
    total_compensation: 3950000,
    confidence_score: 0.91,
    is_verified: true,
  },
  {
    id: 'sal_018',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Software Engineer',
    level_standardized: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 9,
    base_salary: 4200000,
    bonus: 600000,
    stock: 2200000,
    total_compensation: 7000000,
    confidence_score: 0.88,
    is_verified: true,
  },
  {
    id: 'sal_019',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Software Engineer',
    level_standardized: 'Staff',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 14,
    base_salary: 6200000,
    bonus: 1000000,
    stock: 5000000,
    total_compensation: 12200000,
    confidence_score: 0.82,
    is_verified: false,
  },
  {
    id: 'sal_020',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Product Manager',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 6,
    base_salary: 2900000,
    bonus: 400000,
    stock: 1200000,
    total_compensation: 4500000,
    confidence_score: 0.86,
    is_verified: true,
  },
  {
    id: 'sal_021',
    company: 'Microsoft',
    company_slug: 'microsoft',
    role: 'Software Engineer',
    level_standardized: 'L5',
    location: 'New York',
    currency: 'USD',
    experience_years: 10,
    base_salary: 200000,
    bonus: 30000,
    stock: 80000,
    total_compensation: 310000,
    confidence_score: 0.90,
    is_verified: true,
  },

  // ─── Meta (5 records) ────────────────────────────────────────────────
  {
    id: 'sal_022',
    company: 'Meta',
    company_slug: 'meta',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 2000000,
    bonus: 300000,
    stock: 1000000,
    total_compensation: 3300000,
    confidence_score: 0.92,
    is_verified: true,
  },
  {
    id: 'sal_023',
    company: 'Meta',
    company_slug: 'meta',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 3500000,
    bonus: 500000,
    stock: 2500000,
    total_compensation: 6500000,
    confidence_score: 0.89,
    is_verified: true,
  },
  {
    id: 'sal_024',
    company: 'Meta',
    company_slug: 'meta',
    role: 'Software Engineer',
    level_standardized: 'L5',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 8,
    base_salary: 5000000,
    bonus: 800000,
    stock: 4000000,
    total_compensation: 9800000,
    confidence_score: 0.85,
    is_verified: true,
  },
  {
    id: 'sal_025',
    company: 'Meta',
    company_slug: 'meta',
    role: 'Software Engineer',
    level_standardized: 'Staff',
    location: 'San Francisco',
    currency: 'USD',
    experience_years: 14,
    base_salary: 280000,
    bonus: 60000,
    stock: 250000,
    total_compensation: 590000,
    confidence_score: 0.80,
    is_verified: false,
  },
  {
    id: 'sal_026',
    company: 'Meta',
    company_slug: 'meta',
    role: 'Data Scientist',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 3200000,
    bonus: 450000,
    stock: 2200000,
    total_compensation: 5850000,
    confidence_score: 0.87,
    is_verified: true,
  },

  // ─── Flipkart (5 records) ────────────────────────────────────────────
  {
    id: 'sal_027',
    company: 'Flipkart',
    company_slug: 'flipkart',
    role: 'Software Development Engineer',
    level_standardized: 'SDE-I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1500000,
    bonus: 100000,
    stock: 300000,
    total_compensation: 1900000,
    confidence_score: 0.93,
    is_verified: true,
  },
  {
    id: 'sal_028',
    company: 'Flipkart',
    company_slug: 'flipkart',
    role: 'Software Development Engineer',
    level_standardized: 'SDE-II',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2800000,
    bonus: 350000,
    stock: 800000,
    total_compensation: 3950000,
    confidence_score: 0.90,
    is_verified: true,
  },
  {
    id: 'sal_029',
    company: 'Flipkart',
    company_slug: 'flipkart',
    role: 'Software Development Engineer',
    level_standardized: 'SDE-III',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 7,
    base_salary: 3800000,
    bonus: 500000,
    stock: 1500000,
    total_compensation: 5800000,
    confidence_score: 0.87,
    is_verified: true,
  },
  {
    id: 'sal_030',
    company: 'Flipkart',
    company_slug: 'flipkart',
    role: 'Backend Engineer',
    level_standardized: 'SDE-II',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 3000000,
    bonus: 400000,
    stock: 900000,
    total_compensation: 4300000,
    confidence_score: 0.88,
    is_verified: false,
  },
  {
    id: 'sal_031',
    company: 'Flipkart',
    company_slug: 'flipkart',
    role: 'Software Development Engineer',
    level_standardized: 'Staff',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 12,
    base_salary: 5500000,
    bonus: 800000,
    stock: 3500000,
    total_compensation: 9800000,
    confidence_score: 0.79,
    is_verified: false,
  },

  // ─── Meesho (3 records) ──────────────────────────────────────────────
  {
    id: 'sal_032',
    company: 'Meesho',
    company_slug: 'meesho',
    role: 'Software Engineer',
    level_standardized: 'SDE-I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1400000,
    bonus: 100000,
    stock: 200000,
    total_compensation: 1700000,
    confidence_score: 0.91,
    is_verified: true,
  },
  {
    id: 'sal_033',
    company: 'Meesho',
    company_slug: 'meesho',
    role: 'Software Engineer',
    level_standardized: 'SDE-II',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 3,
    base_salary: 2400000,
    bonus: 250000,
    stock: 600000,
    total_compensation: 3250000,
    confidence_score: 0.88,
    is_verified: true,
  },
  {
    id: 'sal_034',
    company: 'Meesho',
    company_slug: 'meesho',
    role: 'Software Engineer',
    level_standardized: 'SDE-III',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 7,
    base_salary: 3600000,
    bonus: 400000,
    stock: 1200000,
    total_compensation: 5200000,
    confidence_score: 0.84,
    is_verified: false,
  },

  // ─── Razorpay (3 records) ────────────────────────────────────────────
  {
    id: 'sal_035',
    company: 'Razorpay',
    company_slug: 'razorpay',
    role: 'Software Engineer',
    level_standardized: 'SDE-I',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 2,
    base_salary: 1300000,
    bonus: 100000,
    stock: 250000,
    total_compensation: 1650000,
    confidence_score: 0.90,
    is_verified: true,
  },
  {
    id: 'sal_036',
    company: 'Razorpay',
    company_slug: 'razorpay',
    role: 'Software Engineer',
    level_standardized: 'SDE-II',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 4,
    base_salary: 2200000,
    bonus: 300000,
    stock: 700000,
    total_compensation: 3200000,
    confidence_score: 0.87,
    is_verified: true,
  },
  {
    id: 'sal_037',
    company: 'Razorpay',
    company_slug: 'razorpay',
    role: 'Backend Engineer',
    level_standardized: 'SDE-III',
    location: 'Pune',
    currency: 'INR',
    experience_years: 6,
    base_salary: 3200000,
    bonus: 400000,
    stock: 1000000,
    total_compensation: 4600000,
    confidence_score: 0.83,
    is_verified: false,
  },

  // ─── Zepto (2 records) — few-record company edge case ────────────────
  {
    id: 'sal_038',
    company: 'Zepto',
    company_slug: 'zepto',
    role: 'Software Engineer',
    level_standardized: 'SDE-I',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 1,
    base_salary: 1200000,
    bonus: 80000,
    stock: 200000,
    total_compensation: 1480000,
    confidence_score: 0.86,
    is_verified: true,
  },
  {
    id: 'sal_039',
    company: 'Zepto',
    company_slug: 'zepto',
    role: 'Software Engineer',
    level_standardized: 'SDE-II',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 3,
    base_salary: 2200000,
    bonus: 200000,
    stock: 500000,
    total_compensation: 2900000,
    confidence_score: 0.82,
    is_verified: false,
  },

  // ─── NVIDIA (3 records) — stock-heavy compensation ───────────────────
  {
    id: 'sal_040',
    company: 'NVIDIA',
    company_slug: 'nvidia',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 2600000,
    bonus: 300000,
    stock: 3500000,
    total_compensation: 6400000,
    confidence_score: 0.90,
    is_verified: true,
  },
  {
    id: 'sal_041',
    company: 'NVIDIA',
    company_slug: 'nvidia',
    role: 'Software Engineer',
    level_standardized: 'L5',
    location: 'Pune',
    currency: 'INR',
    experience_years: 9,
    base_salary: 4000000,
    bonus: 500000,
    stock: 6000000,
    total_compensation: 10500000,
    confidence_score: 0.85,
    is_verified: true,
  },
  {
    id: 'sal_042',
    company: 'NVIDIA',
    company_slug: 'nvidia',
    role: 'Deep Learning Engineer',
    level_standardized: 'Staff',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 14,
    base_salary: 6000000,
    bonus: 1000000,
    stock: 12000000,
    total_compensation: 19000000,
    confidence_score: 0.76,
    is_verified: false,
  },

  // ─── Tata Consultancy Services (5 records) — long company name edge case
  {
    id: 'sal_043',
    company: 'Tata Consultancy Services',
    company_slug: 'tcs',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 1,
    base_salary: 800000,
    bonus: 0,
    stock: 0,
    total_compensation: 800000,
    confidence_score: 0.96,
    is_verified: true,
  },
  {
    id: 'sal_044',
    company: 'Tata Consultancy Services',
    company_slug: 'tcs',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Pune',
    currency: 'INR',
    experience_years: 5,
    base_salary: 1200000,
    bonus: 80000,
    stock: 0,
    total_compensation: 1280000,
    confidence_score: 0.94,
    is_verified: true,
  },
  {
    id: 'sal_045',
    company: 'Tata Consultancy Services',
    company_slug: 'tcs',
    role: 'Systems Engineer',
    level_standardized: 'L3',
    location: 'Delhi NCR',
    currency: 'INR',
    experience_years: 2,
    base_salary: 900000,
    bonus: 50000,
    stock: 0,
    total_compensation: 950000,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    id: 'sal_046',
    company: 'Tata Consultancy Services',
    company_slug: 'tcs',
    role: 'Software Engineer',
    level_standardized: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 10,
    base_salary: 1800000,
    bonus: 150000,
    stock: 0,
    total_compensation: 1950000,
    confidence_score: 0.90,
    is_verified: true,
  },
  {
    id: 'sal_047',
    company: 'Tata Consultancy Services',
    company_slug: 'tcs',
    role: 'Software Architect',
    level_standardized: 'L6',
    location: 'Mumbai',
    currency: 'INR',
    experience_years: 16,
    base_salary: 2800000,
    bonus: 250000,
    stock: 0,
    total_compensation: 3050000,
    confidence_score: 0.85,
    is_verified: false,
  },

  // ─── Infosys (4 records) ─────────────────────────────────────────────
  {
    id: 'sal_048',
    company: 'Infosys',
    company_slug: 'infosys',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 850000,
    bonus: 0,
    stock: 0,
    total_compensation: 850000,
    confidence_score: 0.97,
    is_verified: true,
  },
  {
    id: 'sal_049',
    company: 'Infosys',
    company_slug: 'infosys',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Pune',
    currency: 'INR',
    experience_years: 5,
    base_salary: 1300000,
    bonus: 100000,
    stock: 0,
    total_compensation: 1400000,
    confidence_score: 0.93,
    is_verified: true,
  },
  {
    id: 'sal_050',
    company: 'Infosys',
    company_slug: 'infosys',
    role: 'Technology Lead',
    level_standardized: 'L5',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 10,
    base_salary: 2000000,
    bonus: 200000,
    stock: 0,
    total_compensation: 2200000,
    confidence_score: 0.89,
    is_verified: true,
  },
  {
    id: 'sal_051',
    company: 'Infosys',
    company_slug: 'infosys',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Delhi NCR',
    currency: 'INR',
    experience_years: 2,
    base_salary: 950000,
    bonus: 50000,
    stock: 0,
    total_compensation: 1000000,
    confidence_score: 0.94,
    is_verified: true,
  },

  // ─── Wipro (2 records) ───────────────────────────────────────────────
  {
    id: 'sal_052',
    company: 'Wipro',
    company_slug: 'wipro',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 1,
    base_salary: 800000,
    bonus: 0,
    stock: 0,
    total_compensation: 800000,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    id: 'sal_053',
    company: 'Wipro',
    company_slug: 'wipro',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Hyderabad',
    currency: 'INR',
    experience_years: 6,
    base_salary: 1400000,
    bonus: 100000,
    stock: 0,
    total_compensation: 1500000,
    confidence_score: 0.92,
    is_verified: true,
  },

  // ─── Atlassian (3 records) ───────────────────────────────────────────
  {
    id: 'sal_054',
    company: 'Atlassian',
    company_slug: 'atlassian',
    role: 'Software Engineer',
    level_standardized: 'L3',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 2,
    base_salary: 1800000,
    bonus: 200000,
    stock: 600000,
    total_compensation: 2600000,
    confidence_score: 0.92,
    is_verified: true,
  },
  {
    id: 'sal_055',
    company: 'Atlassian',
    company_slug: 'atlassian',
    role: 'Software Engineer',
    level_standardized: 'L4',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 5,
    base_salary: 3000000,
    bonus: 400000,
    stock: 1500000,
    total_compensation: 4900000,
    confidence_score: 0.89,
    is_verified: true,
  },
  {
    id: 'sal_056',
    company: 'Atlassian',
    company_slug: 'atlassian',
    role: 'Software Engineer',
    level_standardized: 'L5',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 9,
    base_salary: 4800000,
    bonus: 700000,
    stock: 3000000,
    total_compensation: 8500000,
    confidence_score: 0.84,
    is_verified: true,
  },

  // ─── Extra edge case records ─────────────────────────────────────────

  // Very large salary: Principal at Google India — ₹4Cr+ TC
  {
    id: 'sal_057',
    company: 'Google',
    company_slug: 'google',
    role: 'Software Engineer',
    level_standardized: 'Principal',
    location: 'Bengaluru',
    currency: 'INR',
    experience_years: 22,
    base_salary: 12000000,
    bonus: 3000000,
    stock: 25000000,
    total_compensation: 40000000,
    confidence_score: 0.65,
    is_verified: false,
  },
];

/**
 * Returns an array of all unique company slugs present in the salary data.
 */
export function getAllCompanySlugs(): string[] {
  return [...new Set(salaryRecords.map((r) => r.company_slug))];
}

/**
 * Returns an array of all unique role titles present in the salary data.
 */
export function getAllRoles(): string[] {
  return [...new Set(salaryRecords.map((r) => r.role))];
}

/**
 * Returns an array of all unique locations present in the salary data.
 */
export function getAllLocations(): string[] {
  return [...new Set(salaryRecords.map((r) => r.location))];
}

/**
 * Filters salary records by company slug.
 */
export function getRecordsByCompany(slug: string): SalaryRecord[] {
  return salaryRecords.filter((r) => r.company_slug === slug);
}

/**
 * Finds a single salary record by its ID.
 */
export function getRecordById(id: string): SalaryRecord | undefined {
  return salaryRecords.find((r) => r.id === id);
}
